In [112]:
from os import minor
from pathlib import Path
import pandas as pd

root = Path.cwd().parent

In [113]:
data_non_params = pd.read_csv(f"{root}/results/metrics/results_20251214_153421.csv")
data_with_params = pd.read_csv(f"{root}/results/metrics/results_20251214_153421.csv")

# Dataframe no best params

In [114]:
data_non_params.head()

,model,scaler,balancing name,time_training,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
0,LogisticRegression,StandardScaler,SMOTE,0.010137,0.836214,0.836813,0.836214,0.836141,0.903448
1,LogisticRegression,MinMaxScaler,SMOTE,0.018162,0.836777,0.837509,0.836777,0.836689,0.902167
2,LogisticRegression,NaN,SMOTE,0.012335,0.836026,0.836640,0.836026,0.835951,0.903493
3,LogisticRegression,StandardScaler,RandomOverSampler,0.010784,0.832896,0.833467,0.832896,0.832825,0.897526
4,LogisticRegression,MinMaxScaler,RandomOverSampler,0.010128,0.831143,0.831864,0.831143,0.831052,0.896035

In [115]:
print(data_non_params.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   model            72 non-null     object
 1   scaler           48 non-null     object
 2   balancing name   72 non-null     object
 3   time_training    72 non-null     float64
 4   accuracy_score   72 non-null     float64
 5   precision_score  72 non-null     float64
 6   recall_score     72 non-null     float64
 7   f1_score         72 non-null     float64
 8   roc_auc_score    72 non-null     float64
dtypes: float64(6), object(3)
memory usage: 5.2+ KB
None

In [116]:
data_non_params.fillna({"scaler": "Non scaling"}, inplace=True)

In [117]:
data_non_params.head()

,model,scaler,balancing name,time_training,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
0,LogisticRegression,StandardScaler,SMOTE,0.010137,0.836214,0.836813,0.836214,0.836141,0.903448
1,LogisticRegression,MinMaxScaler,SMOTE,0.018162,0.836777,0.837509,0.836777,0.836689,0.902167
2,LogisticRegression,Non scaling,SMOTE,0.012335,0.836026,0.836640,0.836026,0.835951,0.903493
3,LogisticRegression,StandardScaler,RandomOverSampler,0.010784,0.832896,0.833467,0.832896,0.832825,0.897526
4,LogisticRegression,MinMaxScaler,RandomOverSampler,0.010128,0.831143,0.831864,0.831143,0.831052,0.896035

## max i min dla poszczegolnego parametru time acc, pre, recall, f1 roc, z podziałem na model scaler i balancing

In [118]:
score_columns = ['time_training', 'accuracy_score', 'precision_score', 'recall_score', 'f1_score', 'roc_auc_score']

for col in score_columns:
    print(f"--- Analysis for: {col} ---")

    max_row = data_non_params.loc[data_non_params[col].idxmax()]
    print(f"Max {col}:")
    print(f"Model: {max_row.get('model')}, Scaler: {max_row.get('scaler')}, Balancing name: {max_row.get('balancing name')}, Value: {max_row[col]}")

    print("-" * 20)

    min_row = data_non_params.loc[data_non_params[col].idxmin()]
    print(f"Min {col}:")
    print(f"Model: {min_row.get('model')}, Scaler: {min_row.get('scaler')}, Balancing name: {min_row.get('balancing name')}, Value: {min_row[col]}")

    print("\n")

--- Analysis for: time_training ---
Max time_training:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 19.527782201766968
--------------------
Min time_training:
Model: KNeighborsClassifier, Scaler: Non scaling, Balancing name: RandomUnderSampler, Value: 0.0006210803985595


--- Analysis for: accuracy_score ---
Max accuracy_score:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 0.9942399236439998
--------------------
Min accuracy_score:
Model: DecisionTreeClassifier, Scaler: StandardScaler, Balancing name: RandomUnderSampler, Value: 0.7539512254454783


--- Analysis for: precision_score ---
Max precision_score:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 0.9942936325982114
--------------------
Min precision_score:
Model: DecisionTreeClassifier, Scaler: StandardScaler, Balancing name: RandomUnderSampler, Value: 0.7549384333241873


--- Analysis for: recall_score ---
Max recall_score:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 0.9942399236439998
--------------------
Min recall_score:
Model: DecisionTreeClassifier, Scaler: StandardScaler, Balancing name: RandomUnderSampler, Value: 0.7539512254454783


--- Analysis for: f1_score ---
Max f1_score:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 0.9942397651189352
--------------------
Min f1_score:
Model: DecisionTreeClassifier, Scaler: StandardScaler, Balancing name: RandomUnderSampler, Value: 0.7537226420811066


--- Analysis for: roc_auc_score ---
Max roc_auc_score:
Model: RandomForestClassifier, Scaler: StandardScaler, Balancing name: RandomOverSampler, Value: 0.9999061794447536
--------------------
Min roc_auc_score:
Model: DecisionTreeClassifier, Scaler: StandardScaler, Balancing name: RandomUnderSampler, Value: 0.7539847827147247

# Dataframe with best params

In [119]:
data_with_params = pd.read_csv(f"{root}/results/metrics/results_20251213_170700.csv")

In [120]:
data_with_params.head()

,model,scaler,balancing name,time_training,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,best_params
0,LogisticRegression,StandardScaler,SMOTE,2.194893,0.836589,0.837223,0.836589,0.836512,0.903330,"{'clf__C': np.float64(0.30584494295802445), 'c..."
1,LogisticRegression,MinMaxScaler,SMOTE,5.174169,0.837403,0.838090,0.837403,0.837320,0.902508,"{'clf__C': np.float64(1.6599452033620266), 'cl..."
2,LogisticRegression,NaN,SMOTE,1.299297,0.836402,0.837018,0.836402,0.836327,0.903433,"{'clf__C': np.float64(0.30584494295802445), 'c..."
3,LogisticRegression,StandardScaler,RandomOverSampler,0.659358,0.833522,0.834023,0.833522,0.833460,0.897532,"{'clf__C': np.float64(1.6599452033620266), 'cl..."
4,LogisticRegression,MinMaxScaler,RandomOverSampler,6.230961,0.834587,0.835150,0.834587,0.834517,0.896744,"{'clf__C': np.float64(3.845401188473625), 'clf..."

In [121]:
data_with_params.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   model            72 non-null     object
 1   scaler           48 non-null     object
 2   balancing name   72 non-null     object
 3   time_training    63 non-null     float64
 4   accuracy_score   72 non-null     float64
 5   precision_score  63 non-null     float64
 6   recall_score     63 non-null     float64
 7   f1_score         63 non-null     float64
 8   roc_auc_score    63 non-null     float64
 9   best_params      72 non-null     object
dtypes: float64(6), object(4)
memory usage: 5.8+ KB